version: '3.8'
services:
  gowebly_fiber:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      BACKEND_PORT: 8080
    networks:
      - gowebly_fiber_network

networks:
  gowebly_fiber_network:
