// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func PaigeContent() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"app\" class=\"flex flex-col gap-6 justify-center place-items-center md:gap-12 h-fit py-8\"><div class=\"p-12 flex flex-col gap-6 justify-center place-items-center\"><div class=\"h-24 w-24 rounded-full outline outline-offset-2 outline-[#002D62] bg-cover overflow-hidden transition duration-500 cursor-pointer hover:scale-125\"><img src=\"/static/images/paige.jpeg\" class=\"w-full h-full\" alt=\"Paige\"></div><p class=\"text-4xl md:text-6xl text-[#002D62] font-black\">To Paige</p></div><div class=\"flex flex-col justify-center place-items-center text-center w-4/5\"><p class=\"text-lg font-bold\">\"Live the life you love. Love the life you live.\"</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
