// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.590
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func ScratchCard() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"scratch-card\" data-scratch-card><div class=\"scratch-card-header\"><div class=\"scratch-card-badge\">Task</div><p class=\"scratch-card-title\">Scratch the message</p></div><p class=\"scratch-card-subtitle\">Swipe to reveal the note underneath, then refresh for a new one.</p><div class=\"scratch-stage\" data-scratch-stage><div class=\"scratch-message\" data-scratch-message aria-live=\"polite\"></div><canvas class=\"scratch-canvas\" data-scratch-canvas></canvas></div><div class=\"scratch-actions\"><button class=\"btn-primary\" data-scratch-refresh type=\"button\">Refresh message</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
